repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: pretty-format-json
    args: [--autofix]
  - id: detect-private-key
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: no-commit-to-branch
    args: [--branch, main]
  - id: check-yaml
  - id: check-json
  - id: check-added-large-files

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.2.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: []

- repo: local
  hooks:
  - id: dotnet-format
    name: dotnet format
    language: system
    entry: dotnet format
    types: [python, yaml, json, text]
    always_run: true

  - id: dotnet-build
    name: dotnet build
    language: system
    entry: dotnet build
    pass_filenames: false

  - id: dotnet-test
    name: dotnet test
    language: system
    entry: dotnet test
    pass_filenames: false
